In [18]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.io 
from disc_dataset_equalwidth import disc_dataset_equalwidth
from Group_JMI_Rand import Group_JMI_Rand

In [37]:
#Este corre bien
mat = scipy.io.loadmat('/Users/macondo/Documents/GitHub/TFM/Raw_Data/atp1d.mat')

a=mat.items()
b=list(a)
X=np.array(b[3][1])
labels=np.array(b[4][1])


In [ ]:
#Para este dataset se hace uso de la metrica/ditancia "hamming" en la funcion Group_JMI_Rand. 
#Hasta ahora tengo solo la "euclidiana" implememtada y eso me genera error en la funcion (creo yo y viendo la naturaleza de nuestros datos,
#es la que necesitamos (pero tu me corregiras))
mat = scipy.io.loadmat('/Users/macondo/Documents/GitHub/TFM/Raw_Data/emotions.mat')

a=mat.items()
b=list(a)
X=np.array(b[4][1])
labels=np.array(b[3][1])


In [45]:
X

array([[0.034741, 0.089665, 0.091225, ..., 0.245457, 0.105065, 0.405399],
       [0.081374, 0.272747, 0.085733, ..., 0.343547, 0.276366, 0.710924],
       [0.110545, 0.273567, 0.08441 , ..., 0.188693, 0.045941, 0.457372],
       ...,
       [0.035169, 0.065403, 0.075227, ..., 0.184313, 0.247136, 0.476993],
       [0.054276, 0.238158, 0.095935, ..., 0.547126, 0.183494, 1.25582 ],
       [0.073194, 0.140733, 0.080545, ..., 0.087328, 0.236815, 0.451701]])

In [46]:
labels

array([[0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       ...,
       [0, 0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]], dtype=uint8)

In [21]:
bins = 5

In [47]:
X_inputs_disc = disc_dataset_equalwidth(X, bins)

In [48]:
X_inputs_disc

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 1.],
       [2., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [27]:
topK = 10

In [49]:
Selected_with_Group_JMI = Group_JMI_Rand(X_inputs_disc,labels, topK)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 1 is empty! self.labels_[self.medoid_indices_[1]] may not be labeled with its corresponding cluster (1).
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 2 is empty! self.labels_[self.medoid_indices_[2]] may not be labeled with its corresponding cluster (2).
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 3 is empty! self.labels_[self.medoid_indices_[3]] may not be labeled with its corresponding cluster (3).
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 4 is empty! self.labels_[self.medoid_indices_[4]] may not be label

ValueError: attempt to get argmax of an empty sequence

In [43]:
Selected_with_Group_JMI

[80, 47, 308, 116, 277, 29, 92, 125, 305, 146]