In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.io 
from disc_dataset_equalwidth import disc_dataset_equalwidth
from Group_JMI_Rand import Group_JMI_Rand

In [3]:
#Este corre bien
mat = scipy.io.loadmat('/Users/macondo/Documents/GitHub/TFM/Raw_Data/atp1d.mat')

a=mat.items()
b=list(a)
X=np.array(b[3][1])
labels=np.array(b[4][1])


In [4]:
X

array([[ 72.,   1.,  69., ...,   1.,   0.,   0.],
       [ 72.,   1.,  70., ...,   0.,   1.,   0.],
       [ 72.,   1.,  71., ...,   0.,   0.,   1.],
       ...,
       [233.,   1., 142., ...,   0.,   0.,   0.],
       [233.,   1., 143., ...,   0.,   0.,   0.],
       [233.,   1., 144., ...,   0.,   0.,   0.]])

In [5]:
labels

array([[ 788, 1339,  853,  853,  788,  853],
       [ 788, 1339,  853,  853,  788,  853],
       [ 788, 1339,  853,  853,  788,  853],
       ...,
       [ 248,  395,  406,  473,  268,  473],
       [ 248,  299,  406,  450,  268,  450],
       [ 248,  299,  406,  450,  258,  450]], dtype=uint16)

In [6]:
bins = 5

In [7]:
X_inputs_disc = disc_dataset_equalwidth(X, bins)

In [8]:
X_inputs_disc

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [4., 0., 4., ..., 0., 0., 0.],
       [4., 0., 4., ..., 0., 0., 0.],
       [4., 0., 4., ..., 0., 0., 0.]])

In [9]:
topK = 10

In [10]:
Selected_with_Group_JMI = Group_JMI_Rand(X_inputs_disc,labels, topK)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 2 is empty! self.labels_[self.medoid_indices_[2]] may not be labeled with its corresponding cluster (2).
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 6 is empty! self.labels_[self.medoid_indices_[6]] may not be labeled with its corresponding cluster (6).
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 14 is empty! self.labels_[self.medoid_indices_[14]] may not be labeled with its corresponding cluster (14).
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn_extra/cluster/_k_medoids.py:329: UserWarning: Cluster 5 is empty! self.labels_[self.medoid_indices_[5]] may not be la

In [11]:
Selected_with_Group_JMI

[80, 4, 29, 116, 305, 125, 0, 173, 308, 128]